### ISSUE TITLE
Add an explorer's hub topic for support

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/gatsby-theme-newrelic#13]
To comply with our open source standards via the [open source checklist](https://docs.google.com/document/d/1y644Pwi82kasNP5VPVjDV8rsmkBKclQVHFkz8pwRUtE/edit), let's add an explorer's hub topic and link it in the README.

we will first need to update the NPM Package with details https://github.com/newrelic/gatsby-theme-newrelic

And given we don't have any pre-determined guidance for an npm package. 

Will post something similar to what we do with the Nerdpacks which is grab some helpful bits from the README and treat it as an initial "press release" in a sense.

- Screenshot + Intro, what is it and why would you want to use it
- How to use it, install/setup (i.e. npm install)
- Link to the repo

**Comment by jpvajda** [comment]
I might need some clarity with what we are sharing with the Discuss Community @jerelmiller, I'll message you about this to answer a few questions.

**Comment by jpvajda** [comment]
@jerelmiller is going to see how we can update the NPM package listing as it's currently blank right now then I can post this.

**Comment by jpvajda** [comment]
it is done: https://discuss.newrelic.com/t/annoucing-a-new-relic-gatsby-site-theme/109814
