### ISSUE TITLE
simplify the create Issue workflow to not require the use of github templates

### ISSUE THREAD

**Issue by jpvajda** [newrelic/gatsby-theme-newrelic#170]
With the Docs Site we decided to take a streamline approach to have the submit feedback button pass values in the URL using constants, which prevents the need to use a github issue template. This is very streamlined for a user, and it be cool to do this for the developer site as well and be consistent in our approach to creating issues on both sites. 

**code**
https://github.com/newrelic/docs-website/pull/412/files/9d9091d5dbcf34c6eee855b3f89d7a9b92a53406#diff-22bbe242b6fb50d3a94108b9bf5c8b3df5f928f4d29dea68bc3f7e61d32ee26bR26

### considerations

- is this a theme level change or done for each site? Given the The OSS site may need additional issue templates.
- does this makes sense to do for both the Docs Site and Dev Site? 
- why does the OSS Site need so many templates linked from create an issue? can we just by pass that.

### current issue templates
**Docs:**
https://github.com/newrelic/docs-website/issues/new/choose

**Dev Site:**

https://github.com/newrelic/developer-website/issues/new/choose

**OSS Site**

https://github.com/newrelic/opensource-website/issues/new/choose

**Comment by jpvajda** [comment]
I wanted to check in with @djsauble on this from a UX perspective. This approach means we'd have no issue selection step when a user clicks the `create issue` button, but we could still keep the issue templates in Github, for those that go through the issue filing process on github. 

I also think we'd want this functionality in theme, and I need to confirm if OSS really needs to drive a user through a template selection as well.

**Comment by djsauble** [comment]
It's not horrible to have the issue type as part of the issue template. The main downside to doing this vs. having a label is that it's harder to filter to just bugs (for instance). I'd suggest we start here and adjust as needed.

**Comment by jpvajda** [comment]
@djsauble just confirming, you are supporting not using the selection of an issue template? OR keeping it as today?

**Comment by djsauble** [comment]
Yes, I'm saying it's probably fine to not have separate issue templates.

That said, I don't think I've seen the selection process as designed, so maybe I should see that before having too strong of an opinion here.

**Comment by jpvajda** [comment]
Essentially a use clicks on Create an Issue button, and on all DECO sites are taking to [github new issues] screen(https://github.com/newrelic/docs-website/issues/new/choose) where they have to decide and select a template to use. From there, they just complete the issue.

**Comment by djsauble** [comment]
Ah! This isn't bad at all.

So in the feedback case, would we have separate 'thumbs up' and 'thumbs down' templates and skip the selection process entirely?

**Comment by jpvajda** [comment]
@djsauble that's correct, we just thought  we apply the same approach we did for feedback submission to the issue creation workflow,  just bypassing the screen to select the issue template on github.
