### ISSUE TITLE
[NR Browser] Instrument ExternalLink component

### ISSUE THREAD

**Issue by caylahamann** [newrelic/gatsby-theme-newrelic#248]
## Summary 
We need to instrument our `ExternalLink` and `Link`  component with NR Browser. We need to track the following events: 
* `externalLink_click`: occurs when a user clicks on any external link 

Properties that we want to record with this action: 
* `href`: link clicked 

## AC
* [ ] instrumented with NR browser agent 
* [ ] update [spreadsheet](https://docs.google.com/spreadsheets/d/1VmgEp4n-GA3wvIjBy7rJQn3H7k_ytoqxvYG50X8xeAs/edit?usp=sharing) with action name, additional properties, location implemented, ect.

**Comment by jerelmiller** [comment]
Could we change this to instrumenting the `Link` component? `ExternalLink` (should) be deprecated since its functionality is captured in `Link`. `Link` is much smarter these days and will automatically detect external links.

**Comment by caylahamann** [comment]
We need to instrument this for the `Link` component as well
