### ISSUE TITLE
[NR Browser] Instrument SimpleFeedback component

### ISSUE THREAD

**Issue by caylahamann** [newrelic/gatsby-theme-newrelic#250]
## Summary 
We need to instrument our `SimpleFeedback` component with NR Browser. We need to track the following events: 
* `feedback_click`: occurs when a user clicks on one of the feedback buttons 

Properties that we want to record with this action: 
* `feedback`: whether the feedback is positive or negative

## AC
* [x] instrumented with NR browser agent 
* [ ] update [spreadsheet](https://docs.google.com/spreadsheets/d/1VmgEp4n-GA3wvIjBy7rJQn3H7k_ytoqxvYG50X8xeAs/edit?usp=sharing) with action name, additional properties, location implemented, ect.

**Comment by caylahamann** [comment]
we decided the case of tracking whether the user doesn't complete the issue process is out of scope for this mmf

**Comment by jpvajda** [comment]
As a note: we'll be instrumenting the: 

- # of clicks per button
-  Which page did they click it on

so this should be enough data for now, given it's may not possible to instrument specific page action on github itself.
