### ISSUE TITLE
[Google] Add google analytics custom events 

### ISSUE THREAD

**Issue by caylahamann** [newrelic/gatsby-theme-newrelic#254]
## Summary 
To reach parity with the current docs site, we need to send custom google events with GA. We need to track two events (that will be also instrumented with NR browser) `copyCodeBlock_click` and `externalLink_click`. They will send the same info that is sent with NR browser. We can implement this in one of two ways. 

### Option 1: Use global `ga` methods 
We can still access to the global `ga` methods to send custom events, we just won't be sending them through Tessen and therefore Segment. Product analytics folks don't need access to the custom events. You can read more about this [here](https://developers.google.com/analytics/devguides/collection/gajs/eventTrackerGuide).

### Option 2: Use `Tessen.track`
We can also send this through the `tessen.track()` method, but this would also mean we would send it to segment and NR browser (and we are already sending some of these events to NR browser, so to avoid duplication it might be best to option 1). 

## AC 
* [ ] Add GA tracking for `copyCodeBlock_click`
* [ ] Add GA tracking for `externalLink_click` 
* [ ] Check we are on alignment with tracking 

## Helpful links 
* Tracking events with google analytics:  https://developers.google.com/analytics/devguides/collection/gajs/eventTrackerGuide
* [instrumentation tracking spreadsheet](https://docs.google.com/spreadsheets/d/1VmgEp4n-GA3wvIjBy7rJQn3H7k_ytoqxvYG50X8xeAs/edit?usp=sharing)

**Comment by caylahamann** [comment]
Figure out how to link the old attribute to the new one

**Comment by tariqahmed** [comment]
Just a note from Sy Jones: 

Hello this topic has come up quite a few times because we’ve been doing an audit of all the site analytics
and it looks like DOCS is on their own Google analytics code that’s different from the rest of the website

**Comment by caylahamann** [comment]
closing this because we do not need the custom events, everything is already in NR and all events needed by product analytics is automatically available to GA through tessen :)
