### ISSUE TITLE
Improve Theme README/CONTRIBUTING docs

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/gatsby-theme-newrelic#304]
## Summary

We [received from feedback](https://github.com/newrelic/gatsby-theme-newrelic/pull/300#discussion_r586815693) that our README/CONTRIBUTING docs aren't as helpful as they could be to guide a contributor on how to get spun up with the site.

I'd love for us to look at this and see how we can improve them, especially for how to use the demo site to test changes.

**Comment by jpvajda** [comment]
@rudouglas would you be interesting in taking this one on? it could be a good learning opportunity for our theme, and your documentation skills are 👌

**Comment by rudouglas** [comment]
Ya for sure @jpvajda taking a looksy

**Comment by rudouglas** [comment]
@jpvajda this is the PR for the Readme update: https://github.com/newrelic/gatsby-theme-newrelic/pull/401

I was thinking once that's merged it would be good to link to this from the other Repos as an alternative to help get them coding more quicker 😄

**Comment by jpvajda** [comment]
@rudouglas good idea.  I did this a while back for Docs:

https://github.com/newrelic/docs-website/blob/develop/COMPONENT_GUIDE.md

I think it be cool to add a similar page to the OSS Site as we don't mention anything about where to find component information.

https://github.com/newrelic/opensource-website

perhaps we just add an `COMPONENT_GUIDE.md` file and model it after the Doc Site file. 

And the Dev Site has a reference to it theme here: 

https://github.com/newrelic/developer-website/blob/develop/COMPONENT_GUIDE.md

**Comment by rudouglas** [comment]
Also added a Component page to the OSS docs :D
https://github.com/newrelic/opensource-website/pull/785
