### ISSUE TITLE
[Bug Bash] Browser / OS information not showing up for create issue click

### ISSUE THREAD

**Issue by caylahamann** [newrelic/gatsby-theme-newrelic#309]
## Description

Whenever I click on create an issue, there is no browser / os information showing up. I'm currently on a Chrome browser / MacOS Catalina.

## Steps to Reproduce

I'm not sure, no idea why this is happening (maybe it's settings based)

## Expected Behavior

For the browser information / OS information to pop up

### Page
https://docs.newrelic.com/

### Environment
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

Keeping that there to further the point 😄 ^^

**Comment by AubreyHewes** [comment]
I will look at this again tomorrow, I think I know what is happening..
