### ISSUE TITLE
Change "contributing" link in docs sidebar to point to README

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/gatsby-theme-newrelic#328]
## Summary

On the docs site, I'd like the "contributing" link here to go to [the README](https://github.com/newrelic/docs-website/blob/develop/README.md) for the docs site, not the CONTRIBUTING file

![image](https://user-images.githubusercontent.com/55203603/111527748-7c0d9b80-871d-11eb-9252-9a217df970ca.png)

## Possible Solution

This appears to be set in `packages/gatsby-theme-newrelic/gatsby-node.js`:

          return repository
            ? `${repository}/blob/${branch || DEFAULT_BRANCH}/CONTRIBUTING.md`
            : null;

**Comment by austin-schaefer** [comment]
@jpvajda FYI

**Comment by jerelmiller** [comment]
@austin-schaefer you can configure this in Gatsby-config.js! If you add a `contributingUrl` property to `siteMetadata` (per the [docs](https://github.com/newrelic/gatsby-theme-newrelic/blob/develop/packages/gatsby-theme-newrelic/README.md#site-metadata)), this will update that link.

**Comment by jerelmiller** [comment]
Here is where you'll want to add it: https://github.com/newrelic/docs-website/blob/develop/gatsby-config.js#L27

**Comment by jpvajda** [comment]
I don't agree with this. Contributing tells you all you need to know to contribute (hence the name) the readme is just getting you up and running.

**Comment by jerelmiller** [comment]
One other thing I'll mention here is that in talking with @bradleycamacho, I _think_ the idea long-term was to point to the contributing docs in the docs site itself since these are super helpful for everyone.

**Comment by bradleycamacho** [comment]
Yeah, I chatted with @mmfred about this recently. 

The current plan is:

Next sprint I will go through the contributing file again and rewrite a significant portion of it. Originally I left content contribution in there since it made sense to me at the time, but I now realize we definitely should have a specific doc for content contributions. I'll port EVERYTHING content contribution related out of the contributing file.

I suggest we hold off on this for a few weeks and until I get that work done.

**Comment by austin-schaefer** [comment]
@bradleycamacho Sounds good! Can you add a note to your ticket to look at this link as part of that work? I'll close this issue for now.

@jpvajda : I like Jerel/Bradley's suggestion of linking to an actual HTML page on it once we have that written into the style guide. I'd like to keep the sidebar space in particular focused on first-time contributors and small contributions.

**Comment by bradleycamacho** [comment]
@austin-schaefer Created DOC-6667 with a link to this issue
