### ISSUE TITLE
Header improvements: Bigger search

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/gatsby-theme-newrelic#333]
## Summary

There are a few issues with the header:

* It's very few vertical pixels, and therefore important functionality is easy to miss
* The color of the search bar is very subtle
* The search bar is small and blends easily into the background

## Acceptance criteria/plan

1. Work with @austin-schaefer , @Broseberg , @mb-newrelic to understand the need
2. Come up with design, shop it around
3. Implement it across the three sites
4. Watch KPIs on button usage and search and see if usage improves

## Additional context

@austin-schaefer , @mb-newrelic, and @Broseberg reviewed the docs site audit results. This is one the low-hanging fruit things we'd like to look at relatively early.

**Comment by jpvajda** [comment]
@austin-schaefer If you can get a design for this change it's a pretty easy thing to implement, we don't have a dedicated designer on the team at the moment, so if you know of someone who you can bounce this off of, the implementation is relatively straight forward,

**Comment by jerelmiller** [comment]
Don't wait on me, but if I get bored, I'll take a stab at an updated design.

**Comment by jpvajda** [comment]
hah! @jerelmiller get's bored and good things happen. 🎸

**Comment by roadlittledawn** [comment]
This was done as part of home page redesign and was deployed week or so ago
