### ISSUE TITLE
Update Site Logos for Dev, OSS and Docs Site

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/gatsby-theme-newrelic#334]
## Summary

The Brand team has helped us out with new logo designs for docs, dev, and OSS sites. They'll be providing the logos (I've requested SVG format) later today.

> Images are available on a G-Drive, @jpvajda can share the location with whomever picks this up.

## Acceptance Criteria

- [x] Confirm this change has been approved by all stakeholders
- [x] Apply the 3 logos in light and dark mode to Dev, Docs and OSS sites
- [x] Ensure that the logo renders correctly in Dark and Light modes

**Comment by jpvajda** [comment]
Currently we don't have logos,  if we don't have them by tomorrow when we start the sprint it would go into Sprint 2.

**Comment by austin-schaefer** [comment]
Logos are in a Google Drive link I just emailed to @jpvajda and @zstix
