### ISSUE TITLE
Create a Free Account Button multivariant test

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/gatsby-theme-newrelic#356]
## Summary

We'd like to run an experiment with using a brighter color for the "Free Account" button. 

## Desired Behaviour

- [x] The new button for free account is test all of the folllowing variants.

```
* Existing color 
* New Relic Teal #0AB0BF
* New Relic Blue #0069CE

```

- [x] Set each variant at `33%` traffic in split.

- [x] make a component variant of our [button component ](https://github.com/newrelic/gatsby-theme-newrelic/tree/develop/packages/gatsby-theme-newrelic#button)(or maybe its a new button component) 🤔  that will allow us to set the color of the Free Account button at will and also make modifications to it for other A/B tests.

- [ ] Deploy this new button to the all Sites: `DEV / OSS / DOCS` and replace the existing free account button.
- [x] setup split Test for the 3 variants on Split.io 
- [ ] work with the docs team to understand how to manage this testing process > split.io can probably handle the training.

**Comment by aswanson-nr** [comment]
@austin-schaefer Should the `hover` color match the color provided by the split, should it be provided separately, or is the default fine?

**Comment by austin-schaefer** [comment]
Hi @aswanson-nr, I think we probably need some kind of hover state, but I'm not sure what the best approach would be:

* Are there good secondary versions of each color we can use? 
* Can the current hover color work for all three?
* If we don't have workable colors, we could use a hover animations like the buttons on the homepage?

I'm fine if we just use a standard color right now just to get the data flowing, and once we pick a winning pattern we can figure out an ideal matched color for the hover state?

**Comment by aswanson-nr** [comment]
Current status:
* This PR https://github.com/newrelic/gatsby-theme-newrelic/pull/374 is out to create the new button component. After that's merged we can cut a release and update the 3 sites to use the new version.
* The split is created and ready to go in Split.io.

**Comment by aswanson-nr** [comment]
Not quite done yet! Next is merging this into the sites

**Comment by aswanson-nr** [comment]
Site PRs:
* Docs https://github.com/newrelic/docs-website/pull/2099
* Dev https://github.com/newrelic/developer-website/pull/1295
* OSS https://github.com/newrelic/opensource-website/pull/769

The easiest way to test this is to open the site preview, clear your local storage, and refresh the page.
