### ISSUE TITLE
Provide ability to customize callout heading

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/gatsby-theme-newrelic#357]
## Summary

We'd like to run some experiments with the "free account" callouts, including customizing the heading.

Currently the `Tip` text is automatic and can't be tweaked.

## Desired Behaviour

Provide the ability to use a Tip-style callout, but with different text:

* Could be a new component that allows the user to customize the text, but otherwise shares the tip styling
* Could be a tweak to the tip component to pass a paramter that lets us customize the text
* Could be a hacky solution with inline CSS if we just want to do this temporarily and see if it makes a difference

**Comment by jerelmiller** [comment]
@austin-schaefer as [per the docs](https://github.com/newrelic/gatsby-theme-newrelic/tree/develop/packages/gatsby-theme-newrelic#callout), you should be able to pass a `title` prop to the `Callout` component to customize it. It defaults to `tip` for that variant if one isn't provided. See if that works for you.

**Comment by austin-schaefer** [comment]
Oh wow! @Broseberg can you check this out for your callout project when you're back from PTO?

**Comment by austin-schaefer** [comment]
Closing for now. @Broseberg can you investigate, and re-open if we can't find a workaround?

**Comment by jpvajda** [comment]
This can done by anyone who can modify the tip title  to be `null`
```
<Callout variant={Callout.VARIANT.CAUTION} title={null}>
FREE ACCOUNT!!!!
</Callout>
```

this will then not show the default title of a tip. and just show the text within the component. It's a good workaround but longer term if you find we do need a dedicated call out that is for a free account we could add a call out variant fairly easily. 

Code for the variants is here:

https://github.com/newrelic/gatsby-theme-newrelic/blob/72f6c726888f494ebedf57196ce38ac63a630a4b/packages/gatsby-theme-newrelic/src/components/Callout.js#L6
