### ISSUE TITLE
Document our branch protection rules for each site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/gatsby-theme-newrelic#367]
It would be cool to document (maybe with a simple workflow diagram) how each of our sites (Docs, Dev, and OSS) handle branch protection and approvals of PRs. Nothing fancy, just something we can reference when we have questions on what PRs needs approval  and when as a contributor attempts to contribute to the sites.

### Acceptance Criteria

- [x] write down branch protection rules in an internal doc for review
- [x] when complete add to the contributing.md files for each site respectively in a new section
- [x] also include the cool diagram for visual reference. 

### Contributing links

https://github.com/newrelic/docs-website/blob/develop/CONTRIBUTING.md
https://github.com/newrelic/developer-website/blob/develop/CONTRIBUTING.md
https://github.com/newrelic/opensource-website/blob/develop/CONTRIBUTING.md

**Comment by jpvajda** [comment]
Maybe a good task for Ruairi when he joins the team to get him up to speed on the sites? @zstix - thoughts?

**Comment by rudouglas** [comment]
Initial documentation of each site and the Branch Protection rules applied to them
https://docs.google.com/document/d/1O1SGS0i3OmPfvPhylpFe1CTMkE20889iAOF_cMFJ344/edit#

**Comment by rudouglas** [comment]
@jpvajda Proposed Workflow design, let me know if it looks good (and correct) and i'll create one for the other sites
![Docs Site Branch Protection (2)](https://user-images.githubusercontent.com/17122543/116698436-49152380-a9bc-11eb-8eb4-dab21620d0ae.png)

**Comment by jpvajda** [comment]
@rudouglas I dropped some comments in the doc, let me know if you want to discuss.

**Comment by jpvajda** [comment]
also added some more specific AC

**Comment by rudouglas** [comment]
Pr's are all merged now:

https://github.com/newrelic/developer-website/pull/1297
https://github.com/newrelic/opensource-website/pull/768
https://github.com/newrelic/docs-website/pull/2108

**Comment by jpvajda** [comment]
This is awesome! 🧾
