### ISSUE TITLE
Create a `<Split />` component for content contributors to set up their own A/B tests .

### ISSUE THREAD

**Issue by jpvajda** [newrelic/gatsby-theme-newrelic#369]
Create a <Split /> component for content contributors to set up their own A/B tests (provided they have access to split.io)

### PreReq
Let's first finish this issue https://github.com/newrelic/docs-website/issues/1948 before trying to make this component so we better understand our approach to a/b testing the docs site.

### Approach 

```
<Split test="docssite_paragraph" variant="a">
    This is treatment A
</Split>

<Split test="docssite_paragraph" variant="b">
   This is treatment B
</Split>
```

```
<Split test="banner-test" variant="a">
  <Banner visible={visible} onClose={() => setVisible(false)}>
      <h1>Hello, World!</h1>
  </Banner>
</Split>

<Split test="banner-test" variant="b">
  <Banner visible={visible} onClose={() => setVisible(false)}>
        <h1>Hello, World!</h1>
</Banner>
</Split>
```

### Acceptance Criteria 

- [ ] A contributor can use this component to run a split test on a site. 
- [ ] This component can be a parent component and a child component can be referenced inside of it, so a user could theoretically  set a split test on something like a `banner` component.
- [ ] OR this component could be used as a stand alone component where a user could insert content inside the body of the component.
- [ ] Fully Document this new component in our [component documentation](https://github.com/newrelic/gatsby-theme-newrelic/tree/develop/packages/gatsby-theme-newrelic#components)

**Comment by austin-schaefer** [comment]
That looks good, one idea @jpvajda should we wrap the whole thing in a thing that identifies it as a split test, similar to the syntax we use for collapsers? That way it's less syntactically ambiguous where the split test begins and ends.

For example:

```<SplitGroup>

<Split test="docssite_paragraph" variant="a">
    This is treatment A
</Split>

<Split test="docssite_paragraph" variant="b">
   This is treatment B
</Split>

</SplitGroup>```

**Comment by jpvajda** [comment]
@austin-schaefer Not sure on that approach, but I'll let the engineers decide on syntax. The proposed syntax  has a clear start / end point, it seems a little verbose to add another component around that, unless you are saying you want to group many split tests together where having a group wrapper around those would make sense.

**Comment by x8a** [comment]
Hi! I'm trying to see whether I could work on this issue but I'm not very familiar with split.io and have some questions:
- How would we link split.io to make it display the content of the `<Split />` component?
- Would we display one document with both variants one after the other or the document split by two with one variant on the left and the other on the right?

**Comment by jpvajda** [comment]
@x8a 👋 

here are some docs about using split  at new relic 

https://github.com/newrelic/gatsby-theme-newrelic/tree/develop/packages/gatsby-theme-newrelic#splitio

https://github.com/newrelic/docs-website/blob/develop/CONTRIBUTING.md#split-testing-and-running-experiments


> How would we link split.io to make it display the content of the <Split /> component?

there is an SDK we use to ingrate with the split API and the tests are defined with Split's interface (UI), which is where you set up and run , measure a test. We have a test running currently for the sign up buttons. You can probably learn more about how we use it by paring with one of our engineers as it's probably easier to be walked through it then reading all their docs. 😅 

> Would we display one document with both variants one after the other or the document split by two with one variant on the left and the other on the right?

I think it would depend on the test being run and what you are attempting to do. I can see a case for both if say you were testing the location of a `content block` on the left / right side of a page.  I think a split component for content (say a paragraph of text, or a heading, etc)  really would be location agnostic, and could go anywhere on a page.

For the case of a parent / child test like mentioned above,  you may decide to run a test for a banner on a page.

@aswanson-nr offered to do a 30 minute call with on this as well, so I'll add him to the discusssion as there is a lot to consider for this issue.

**Comment by x8a** [comment]
Thanks so much for the info, @jpvajda! I met with @aswanson-nr and he gave me a great walkthrough 👏🏻👏🏻👏🏻!

@Broseberg explained the use case for this new component to me. The need is not to have a generic component for any type of test writers want to run, but to have a specific test for clicked links. That is, last week we added some links to create a New Relic account to some docs ([here](https://docs.google.com/spreadsheets/d/14cK0fPiRkKSs0hjSGylXuBsVKcEurWaPKMuh4IMmcXA/edit#gid=0)'s the list of edited docs), and we want to see which one is clicked more times to see what language works best to engage users to create a New Relic account. Since the link is the same in the different uses of language, I guess I'll need to embed the link in an extra <p> element to be able to grasp the context.

**Comment by jpvajda** [comment]
This work is account for in #5018 so closing as a duplicate.
