### ISSUE TITLE
👍 and  👎 on content pages should send data to Tessen

### ISSUE THREAD

**Issue by jpvajda** [newrelic/gatsby-theme-newrelic#373]
We currently send these "feedback" inputs to Github which creates an issue, this isn't resulting in much useful feedback on content pages, so let's instead send that data via tessen to the analytics pipeline.  This data will be used for 2021 OKRs

### Acceptance criteria

- [ ] setup new events for each thumb type.  `TDOC_DocPage_feedback_positive` `TDOC_DocPage_feedback_negative`
- [ ] send this event via tessen to the analytics pipeline 
- [ ] if a user clicks yes / no on a page replace the thumbs with a `thank you for your feedback!` message. 
- [ ] if a user comes back to the page later or refreshes a page, we would allow them to `AGAIN` thumb up / down the page.
- [ ] setup an NR1 dashboard chart to provide insights into these events
- [ ] ensure the page URL is also available in NewRelic.
- [ ] update our [documents on analytics](https://github.com/newrelic/docs-website/wiki/Event-Data--and--Instrumentation#tessen-events)

**Comment by jpvajda** [comment]
I wanted to get @austin-schaefer  and Zoe to provide some feedback on this as well.

**Comment by jpvajda** [comment]
What occurs if a user clicks yes / no do we remove the thumbs? and replace with a thank you for your feedback message. if a user comes back to the page, on a refresh..ideally  we would allow them to thumb up / down the page so they don't spam

**Comment by LizBaker** [comment]
@jpvajda just for some clarity: are we keeping the current functionality which opens an issue and prompts for more feedback?

**Comment by jpvajda** [comment]
@LizBaker no we'd replace that, and just send the event for the 👍  or 👎 to Tessen. So essentially we'd disable the issue creation on Github for actual tessen event data, which was the original ask before GA. 🥇
