### ISSUE TITLE
Change "edit" button destination to directly edit page

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/gatsby-theme-newrelic#382]
### Feature

Currently the "edit" button in the sidebar takes you to pages like this:

* https://github.com/newrelic/docs-website/blob/develop/src/content/docs/agents/net-agent/configuration/net-agent-configuration.mdx

I'd love if we could save users a click and take them straight to edit pages like this:

* https://github.com/newrelic/docs-website/edit/develop/src/content/docs/agents/net-agent/configuration/net-agent-configuration.mdx

The GitHub UI around editing is a bit obscure, and I often see people struggle to locate the pencil button. My hypothesis is that removing a click will ultimately increase edits to the site.

### Acceptance Criteria

- [ ]  change  the [prop](https://github.com/newrelic/gatsby-theme-newrelic/blob/fd5cae619f53eaf003859c6b41817de8b8e8fa56/packages/gatsby-theme-newrelic/src/components/EditPageButton.js#L42) of the `EditPageButton.js` of the auto-generated path that includes `/blob/` to `/edit/`.

### Direct Edit Case

A user who has write access to the repo should be able to open  the file directly in the GH editor.

### Forking Case

A user without edit writes on the repo would need to fork if youre not a contributor. previously, you were just looking at the raw file. now youd be looking at a fork prompt, which is a step closer to actually making the change.

### logged out Case

I've tested and if you're not currently logged into GitHub, you'll be prompted to login and then redirected back to the edit page.

**Comment by jpvajda** [comment]
@austin-schaefer just to confirm, if we take this approach any user **not logged** into Github, will be shown the login flow, where the current setup allows the user to few the page content since it's public.

**Comment by nr-kkenney** [comment]
once logged in, you would see this if you are an external user:
![Screen Shot 2021-05-07 at 11 22 16 AM](https://user-images.githubusercontent.com/70179215/117492496-86326600-af26-11eb-8ed5-462e334d00cc.png)

and if you already have this repo forked, you would see:
![Screen Shot 2021-05-07 at 11 23 21 AM](https://user-images.githubusercontent.com/70179215/117492634-b8dc5e80-af26-11eb-9e8d-026f5e410c61.png)

**Comment by jpvajda** [comment]
After discussing this in detail I don't think we want to take this approach as it will force a github non-logged in user (which is likely most users externally) to be pushed through a login flow, where if they don't have a GH account it gets really confusing what is going on here, as they intended to edit the page. I think this approach proposed works well for people that have GH accounts and are accustomed to the workflow of using GH, but it makes it weird for a user who has no concept of GH. At least with the current approach, they can see the MDX file on GH without logging in.

**Comment by austin-schaefer** [comment]
@jpvajda : I'm okay won't-fixing this for now then. Can always return to this in future if the current edit workflow seems to be causing significant friction.

**Comment by jpvajda** [comment]
closing as won't for now.
