### ISSUE TITLE
Keyboard shortcut to hide collapsers

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/gatsby-theme-newrelic#404]
## Summary

We have a keyboard shortcut to open all collapsers (`s` or `CMD+F`), but not to hide them. We had both in Drupal site, which made navigating the page just a little more pleasant.

It would be nice to implement this before/alongside #403 

## Desired Behaviour

Hitting `h` would open all collapsers on the page.

## Possible Solution

@jerelmiller implemented the `s` and `CMD+F` triggers to open collapsers in https://github.com/newrelic/docs-website/issues/760 . He might also have some insight into how to do this for hiding collapsers.

**Comment by jerelmiller** [comment]
@austin-schaefer the ability to hide the collapsers is already in place. If you hit `h`, it will close all collapsers. I just confirmed this works on a doc with collapsers. I was able to open all of them with `s` and close them all again with `h`.

Are you seeing something different?

**Comment by austin-schaefer** [comment]
@jerelmiller 🤦  Just realized Vimium (browser extension for keyboard shortcuts) was intercepting the `h`. Closing as user error.

**Comment by jerelmiller** [comment]
That would do it! 😆
