### ISSUE TITLE
Research the no-referrer-when-downgrade option to track which pages people sign up from

### ISSUE THREAD

**Issue by zoezhou1113** [newrelic/gatsby-theme-newrelic#432]
## Summary

I just realized we are not tracking the individual pages where people click on the signup button from on the docs site. For example, if you click on the "Free account" button from https://docs.newrelic.com/docs/accounts/, the referrer of the TLMK_SignUp_signup event is the homepage (https://docs.newrelic.com/), not https://docs.newrelic.com/docs/accounts/.

![image](https://user-images.githubusercontent.com/80297589/127910830-a1865695-baf5-4ce8-a025-9beae65ffcd7.png)

## Desired Behavior

The desired behavior is for the "referrer" to be the individual page URLs.

## Possible Solution

We need to swap the default policy for docs.newrelic.com (and the other sites) to no-referrer-when-downgrade. Documentation: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

The Referrer-Policy HTTP header controls how much referrer information (sent via the Referer header) should be included with requests. Aside from the HTTP header, you can set this policy in HTML.

I'm not sure if what kind of impact this would have on the website. Could you research whether it's possible to implement this change?

**Comment by roadlittledawn** [comment]
This was implemented about a month ago
