### ISSUE TITLE
Referrer data is missing from segment for signup events `TLMK_SignUp_signup`

### ISSUE THREAD

**Issue by jpvajda** [newrelic/gatsby-theme-newrelic#437]
It looks like we lost the ability to track referrer again when our sites are sending traffic to other subdomains. this issue seems to start on `8/4/21` this is occuring on all sites: `Dev` `Docs` and `OSS`. 

`note` in this case all referrer data is missing. [Last time,](https://github.com/newrelic/docs-website/issues/1816) fixed an issue like this we didn't track at the page level, only have referrer set to docs.newrelic.com

### Steps to Reproduce 

For example, when you click on the "Free Account" button on `docs.newrelic.com` or `developer.newrelic.com` or `opensource.newrelic.com` the referrer of the TLMK_SignUp_signup event is null.

![image (1)](https://user-images.githubusercontent.com/1395158/130147014-7c3e5f11-fd5d-4692-b30d-1c2fc19722b9.png)

`note` discuss.newrelic.com does work.

<img width="732" alt="Screen Shot 2021-08-19 at 3 54 38 PM" src="https://user-images.githubusercontent.com/1395158/130149442-5917417c-2d16-4a19-91fe-976c7dcb70ab.png">

### Expected 

- The referrer of the `TLMK_SignUp_signup` event is NOT null.
- All links to or buttons that push user to the sign up flow  should be  tracked with referrer

### Site PRS

https://github.com/newrelic/docs-website/pull/3567 > `will be released with next docs prod deploy`

https://github.com/newrelic/opensource-website/pull/823 > `released`

https://github.com/newrelic/developer-website/pull/1521  > `released`

**Comment by jpvajda** [comment]
We took a look at this and it seems our 3 gatsby sites are not sending this event `TLMK_SignUp_signup` through segment but a site like discuss is passing the event. So it's not clear exactly where the problem may lie at this moment.

It's possible upgrading our use of [segment to Analytics.js 2.0 may fix this issue](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2/)

**Comment by roadlittledawn** [comment]
Looking at this thread for clues. https://github.com/gatsbyjs/gatsby/issues/18583

Not sure what our `referrer-policy` was in Amplify, but on Gatsby Cloud it's `same-origin`. Which if I'm understanding correctly, it means we would not forward the referrer to signup.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

![2021-08-19_15-20-01](https://user-images.githubusercontent.com/2952843/130151775-b28ca712-87e0-4f75-974d-01c92e77375b.png)

i _think_ setting it to something like [`strict-origin`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy#strict-origin) or [`strict-origin-when-cross-origin`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy#strict-origin-when-cross-origin) would fix it.

far as i can tell, we could explicitly add [`gatsby-plugin-gatsby-cloud`](https://www.gatsbyjs.com/plugins/gatsby-plugin-gatsby-cloud/) and add a `referrer-policy` header setting. or ask them to change it on their end.

**Comment by jpvajda** [comment]
`root cause`  :gatsby: :cloud: handles refferer differently than :aws:  So we had to make a change to the  plugin for gatsby cloud


```
     { 
      resolve: 'gatsby-plugin-gatsby-cloud',
      options: {
        allPageHeaders: ['Referrer-Policy: strict-origin'],
      },
```
