### ISSUE TITLE
remove bizable script from all sites

### ISSUE THREAD

**Issue by jpvajda** [newrelic/gatsby-theme-newrelic#440]
Related issue : https://github.com/newrelic/docs-website/issues/103

PLG and marketing approved the removal of this script as it's the biggest cause of delay  at 1.2s under the category: Eliminate render-blocking resources so we'd love to remove it to reduce that impact. 

### Acceptance Criteria

- [x] See [Lighthouse report](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fdocs.newrelic.com) for details
- [X] Remove script from docs site 
- [X] ensure OSS and Dev sites do not have this script, if they do remove them as well.
- [X] When theme is [updated and released](https://github.com/newrelic/gatsby-theme-newrelic/pull/443) bump theme version on all sites. 

### PRS:

OSS: https://github.com/newrelic/opensource-website/pull/827
DEV: https://github.com/newrelic/developer-website/pull/1562
DOCS: https://github.com/newrelic/docs-website/pull/3695

**Comment by zstix** [comment]
Theme has been bumped and all the related PRs have been merged. These updates should be going our shortly!
