### ISSUE TITLE
[Public Catalog] Update global footer for I/O 

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/gatsby-theme-newrelic#444]
## Summary

On the quickstarts landing and details pages, we want to display a TBD new logo instead of Developers logo in the footer.

## Acceptance criteria
- [x] When viewing the quickstarts landing page or a quickstart details page, the new logo is displayed instead of Developers site logo
- [x] Footer should maintain the same width as the main content.

Removed previous acceptance criteria of having the logo link and on click redirect you to the instant observability page. This would be easy if the site was separate (and it may be in the future), but while it lives within the developer site, is difficult to implement. It will retain the default functionality.

## Helpful links
Relates to #1414 
Relates to https://github.com/newrelic/developer-website/issues/1534

**Comment by nr-kkenney** [comment]
hopefully this is a decent handoff for whoever picks this up:

* I removed the acceptance criteria of having the logo redirect you to IO and explained it above. This was discussed with clinton & zack.
* my current branch `io_global_footer` should be almost complete, with the only thing missing being the final logo we will use for IO. I may have missed something, but the logic for choosing the logo, as well as the styling for the footer to match main content width is implemented.
