### ISSUE TITLE
[Public Catalog] Change Nav Links when we merge the QuickStart Feature Branch

### ISSUE THREAD

**Issue by rudouglas** [newrelic/gatsby-theme-newrelic#450]
## Description

The links in the Global Header are currently set to https://observabilitypacks.gatsbyjs.io/instant-observability/ so that we have a working nav for demoing. Once we merge into the main `developer` branch we will need to change these to `https://developer.newrelic.com/instant-observability/`.

Related to #449 

## Acceptance Criteria

 - [ ] Global Header Nav links to `Instant Observability` on the developer site

**Comment by jpvajda** [comment]
should be covered, but @rudouglas will confirm...
