### ISSUE TITLE
Setup a `next release` branch for the Gatsby Theme

### ISSUE THREAD

**Issue by rudouglas** [newrelic/gatsby-theme-newrelic#457]
Having a next release branch would mean we could test changes to the theme on other sites before release, at the moment, i'm putting the changes in the theme in the node_modules folder at the moment, and maybe there's a different way to do this but a next branch would be ideal

**Comment by jpvajda** [comment]
great idea! I added as a 🅿️ for today's standup.

**Comment by jpvajda** [comment]
I think our decision was to not do this, but @rudouglas if you want to add some details to what we decided that be 🆒

**Comment by aswanson-nr** [comment]
@rudouglas Have you looked into any of these options for running dev content? https://www.gatsbyjs.com/docs/creating-a-local-plugin/#using-requireresolve-and-a-filepath

**Comment by jpvajda** [comment]
Tagged for sustaining epic...  🏗️

**Comment by rudouglas** [comment]
Here is the approach i took. I wrote a Node script we can run locally to publish a new version of the theme to NPM.
The version is specific to the current working branch and also allows for additional versioning e.g

1. I'm working on theme `1.0.0`.
2. I create a new branch called `ru-patch` and make some updates
3. Running the script will create a new version `1.0.0-ru-patch.1` with tag `ru-patch` in NPM
4. I can install this version using the tag/branch name like `yarn add gatsby-theme-newrelic@ru-patch`
4. I make some more updates and run the script again
5. This will create a new version `1.0.0-ru-patch.2` with tag `ru-patch` in NPM
6. Running `yarn add gatsby-theme-newrelic@ru-patch` should pull the latest version `1.0.0-ru-patch.2`

<details>
<summary>Additional Features</summary>

1. Will check that the NPM_TOKEN environment variable has been set
2. Will check you are running Node 16
3. Will check for discrepancies between `yarn.lock` and `package.json`
4. Will check if you are on excluded branches like `main`/`develop`
</details>

You could test this with any repo, but i used this one: https://github.com/rudouglas/gatsby-build-newrelic
All you need is:
 - Create a new publish token in NPM
 - Change the `"name": "ruairi-test"` in `package.json` to something else

### Remaining Questions
I wasn't 100% sure how the current release works, so not sure what happens if I merge a branch with version `1.0.0-ru-patch.1` into main branch with version `1.0.0`, how does semantic versioning deal with that?

**Comment by rudouglas** [comment]
Terminal output:
<img width="604" alt="Screenshot 2021-11-12 at 18 30 16" src="https://user-images.githubusercontent.com/17122543/141517069-c399b405-ac19-4a37-bfce-80f82014f266.png">

**Comment by jerelmiller** [comment]
Since we are using [lerna](https://github.com/lerna/lerna) for releases, could we just use that tool to publish [alpha releases](https://github.com/lerna/lerna/tree/main/commands/publish#--canary) instead? That would avoid the need for a custom script.

**Comment by rudouglas** [comment]
Questions that came up in our Review:

1. Do we want to publish every branch to NPM? This would result in a lot more versions, but does this matter? [Gatsby currently has over 2,000](https://www.npmjs.com/package/gatsby)
2. We could limit the branches pushed to only those containing a specific phrase such as `alpha` etc
3. What happens if we publish a secret to NPM? We could either review every Push before publishing, or we need an `unpublish` workflow in place

**Comment by rudouglas** [comment]
@jerelmiller AFAIK we tried this before without much success, but i'm gonna chat with @aswanson-nr  and @zstix to get more context on why that wasn't working

**Comment by jpvajda** [comment]
@jerelmiller - Thank you! -  You are welcome to be part of the  conversation.. we appreciate your input here. 😄

**Comment by jpvajda** [comment]
>  Do we want to publish every branch to NPM? This would result in a lot more versions, but does this matter? Gatsby currently has over 2,000

That seems unnecessary as this is just a theme, just my 2 cents 

>     We could limit the branches pushed to only those containing a specific phrase such as alpha etc

I like this!

    What happens if we publish a secret to NPM? We could either review every Push before publishing, or we need an unpublish workflow in place

> definitely worth considering this risk.

**Comment by jerelmiller** [comment]
> We could limit the branches pushed to only those containing a specific phrase such as alpha etc

I second this. I like this idea. Perhaps we could combine the branch naming convention + publish when opening a PR through GitHub actions. When a PR is opened, the GitHub action would run, check to see if the branch matches the predefined pattern, and if so, publish an alpha release. This would help both limit the number of versions published and reduce risk on secrets getting published.

If we go this route, we'll also want to consider what happens if a PR is opened and new commits are pushed. `lerna` publishes alpha versions using the commit sha, so new commits means you could have several publishes for a single PR. Depending on the number of times a developer pushes to the branch while the PR is open could result in quite a few releases.

**Comment by jerelmiller** [comment]
I know we aren't the only ones that need something like this, so it might be good if we can identify a few other open source projects that do something similar. Stealing from prior art can help solidify the direction as well 😄
