### ISSUE TITLE
Integrations for Tessen Track Events on Developer and Open Source

### ISSUE THREAD

**Issue by zoezhou1113** [newrelic/gatsby-theme-newrelic#477]
## Description
Currently, the developer and open source sites are not sending `track` events to downstream applications.

## Steps to Reproduce

1. Open Debugger in Segment for either website
2. Click on a track event
3. Look for the "integrations: {}" object

## Expected Behaviour

 "integrations": {
    "All": **true**,
    "Amazon Kinesis Firehose": true,
    "Intercom": true
  },

## Relevant Logs / Console output

![image](https://user-images.githubusercontent.com/80297589/134029361-b19d5d0b-e5b7-4859-96c9-62a99636804f.png)

## Additional context

Note this issue was previously reported for all Deven sites but was only fixed for Docs.

**Comment by roadlittledawn** [comment]
Related to https://github.com/newrelic/gatsby-theme-newrelic/pull/337

**Comment by roadlittledawn** [comment]
this is an odd one. for every `.page()` event we send (which we send for each page load / view), tessen seems to automatically send a related `.track()` event as well (i don't believe we are directly firing `tessen.track()`). that automatically fired event does not take the `integrations.All = true` setting we apply to all the events we fire. you can see that setting on our events like the `.page()` events or in a `track()` we fire (clicking on Free account button for example).

**Comment by roadlittledawn** [comment]
also, looks like this default may have changed with latest version of Tessen

**Comment by zoezhou1113** [comment]
@roadlittledawn  This has been resolved now

**Comment by roadlittledawn** [comment]
we just deployed same on opensource and i'm seeing same as developer, so we should be good to go
