### ISSUE TITLE
[Tessen] Update referrer tracking to capture the full URL  NOT just the path

### ISSUE THREAD

**Issue by zoezhou1113** [newrelic/gatsby-theme-newrelic#489]
## Description

This is not a top priority issue. Currently, `context.page.referrer` only captures the path for the internal referrer, and the full URL for the external referrer. The logic should be consistent so we can parse them through the same URL parsing functions.

`note:` this is an issue for all gatsby sites

## Steps to Reproduce
1. Click on other pages on https://developer.newrelic.com/
2. Check the referrer tracking using the Segment Event Tracker extension

## Expected Behaviour
Full URLs are captured for all events

## Additional context
![image](https://user-images.githubusercontent.com/80297589/135461380-73ae1bd4-2505-456d-b3d7-8b07670bcfbf.png)

**Comment by jpvajda** [comment]
@zoezhou1113 is this just an issue on the developer site? Or is this occuring for all our Gatsby sites, I noticed you created this bug in the theme so I was curious

**Comment by zoezhou1113** [comment]
@jpvajda It's on all of them

**Comment by jpvajda** [comment]
👍

**Comment by jpvajda** [comment]
@roadlittledawn the team reviewed this and had some questions: 

- we did work to add referrer url in this [PR ](https://github.com/newrelic/gatsby-theme-newrelic/pull/460) but it's possible we never passed the full path, is that also your thoughts?

**Comment by roadlittledawn** [comment]
@zoezhou1113 i believe the only way we can affect `context.page.referrer` is via setting a directive for the `Referrer-Policy`. we did that previously to set the full URL for referrer when going cross-domain. is there another directive you know of that gets us full URLs when on same domain AND cross domain?

**Comment by zoezhou1113** [comment]
@roadlittledawn I believe for newrelic.com it's just automatically set by Segment: https://segment.com/docs/connections/spec/page/#properties

**Comment by roadlittledawn** [comment]
only other thing we may be able to do is update the `properties.referrer` to the full URL. Kris and I are looking at the analyrics.js code and it seems like we may be overriding the `context.page.referrer` with the value in `properties.referrer`. that didn't seem to be the case with `properties.search` which is a "reserved name" but we set for searches on I/O landing page.

**Comment by zoezhou1113** [comment]
@nr-kkenney This is perfect. Thank you!
