### ISSUE TITLE
[Tessen] context_ip not recorded in Tessen events

### ISSUE THREAD

**Issue by zoezhou1113** [newrelic/gatsby-theme-newrelic#490]
## Description

Now that we have the cookie policy instrumented via OneTrust, all of the Tessen page and track events need to be updated to track the visitor IP address in the context.ip object. This will allow us to perform analysis on geolocation and detect potential bot behaviors.

## Expected Behaviour
 

- [ ] IPs are available in segment and visible when a use accepts a cookie. 
- [ ] `note` this fix should be applied to all Gatsby sites.

### not working
<img width="811" alt="Screen Shot 2021-10-01 at 12 33 50 PM" src="https://user-images.githubusercontent.com/1395158/135670200-ac6da6f8-2a15-44ac-910d-4a0c494a85b7.png">)

**Comment by jpvajda** [comment]
@zoezhou1113 I assume you want this for all Gatsby sites?

**Comment by zoezhou1113** [comment]
@jpvajda That's correct

**Comment by jpvajda** [comment]
@zoezhou1113 just wanted to confirm: IPs are available in segment and visible ONLY when a use accepts a cookie?

**Comment by zoezhou1113** [comment]
@jpvajda Are you asking how it's working now or now it should behave?

**Comment by jpvajda** [comment]
@zoezhou1113 the expected behavior, so how it should behave.

**Comment by zoezhou1113** [comment]
@jpvajda I think cookie consent should only be required for EMEA, and this should be controlled by OneTrust, but I'm not 100% sure. I'm asking David to give me access to OneTrust so I can take a look.

**Comment by roadlittledawn** [comment]
just want to clarify. in the first AC, you say "when a use [sic] accepts a cookie" what do you mean? since onetrust is essentially doing all the work, we don't really have a way to ask onetrust if we're good to optionally track something extra via Tessen.

**Comment by roadlittledawn** [comment]
also, i'm seeing IP addresses in the data flowing into segment for all 3 gatsby sites. what events don't have this data?

**Comment by jpvajda** [comment]
@zoezhou1113 ☝️

**Comment by zoezhou1113** [comment]
@roadlittledawn you are right. It was probably because of an issue with the data source I was using. You may close the ticket for now.
