### ISSUE TITLE
[Theme] Add a `overlay` modal component to theme

### ISSUE THREAD

**Issue by jpvajda** [newrelic/gatsby-theme-newrelic#499]
We've had several requests to be able to load and play a video in a popover modal, as currently we can only embed a video in a markdown page with our video component.

**Use cases**

Is to in the case of the New Relic I/O Banner on dev site page We'd want to add a second button beside the first so the Main CTA button `▶ How to install` would have an `Action:` popover video modal.
and the Second CTA   `Learn more` would have an `Action` that links to the [existing docs page](https://docs.newrelic.com/docs/full-stack-observability/observe-everything/get-started/new-relic-quickstarts-overview/)

show a image in a "lightbox" for the docs site. 

### Design Questions

- [ ] can we get access to wistia and you tube playback data
- [ ] do we need to run an a/b test to validate our approach
- [ ] how big should this modal be?
- [ ] should it slide in from the top or side? 
- [ ] should the page behind be grayed out?
- [ ] is there a UX best practice we should follow when playing a video in this way?

### Acceptance Criteria 

- [ ] add this new component to our theme for use by our sites 
- [ ] component can support a video or an image

**Comment by austin-schaefer** [comment]
For image and video lightboxes, we should also close the overlay when the user hits escape.

**Comment by legnaleama** [comment]
Quick update here:

I suggest we use the *[Popover Embeds](https://wistia.com/support/embed-and-share/media-on-your-website#popover-embeds)* option from Wistia before creating any new modal component.

**Comment by roadlittledawn** [comment]
Moved to jira
