### ISSUE TITLE
[Theme] Setup `A/B` Sign up button test

### ISSUE THREAD

**Issue by jpvajda** [newrelic/gatsby-theme-newrelic#508]
Run a test on our global header sign up button again  with `Start now`  vs.` Free account`  as the button terms. 

Note: You will need to request access to split.io if you don't already have it.
Split is fairly easy to get set up in your component, here is an [example](https://github.com/newrelic/gatsby-theme-newrelic/commit/044e34e6e97ff34149ecb8ca166d7ec75db53c5c#diff-c3e9cf10d34504caf408d39e6042ae504aaa642bba82ab1778b62109e771ba8eL1-L56) 

### Acceptance Criteria

- [x] Setup a split test to run for 2 weeks on different button language 
- [x] Start now vs Free account
- [x] After there is a winner, we can compare that against `Sign up` in our next A/B Test round
- [x] Create new issue for next test #518

**Comment by jpvajda** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Developer-Enablement-6053b30f8d34df0016400d7b/issues/newrelic/gatsby-theme-newrelic/508?planning-poker) with ZenHub @roadlittledawn

**Comment by tabathadelane** [comment]
I created a new split in Split IO called `deven_signupbutton_text` with a 50/50 rule on "Start now" vs "Free account."
