### ISSUE TITLE
[SEO] Add sitelinks searchbox snippet

### ISSUE THREAD

**Issue by LizBaker** [newrelic/gatsby-theme-newrelic#516]
Google sometimes renders a searchbox for a given result. This box can either return search results based on google's engine, or it can return results based on your site's internal search. To use your site's search you need to add a particular script. Unfortunately this won't increase our chances of having a searchbox in the results, but it means that our search will be used if that ever happens.

In the event that we do get a searchbox we can have this code ready to go so that our own search is leveraged.
[More info here](https://developers.google.com/search/docs/advanced/structured-data/sitelinks-searchbox)

### Acceptance Criteria

- [x] Add a script tag with structured data in the theme seo component. google advises that this is done on the homepage and only done once
- [x] Update the theme in Docs
- [x] Test that it is added correctly using https://search.google.com/test/rich-results
- [ ] cross your fingers that we get a searchbox one of these days 🤞

**Comment by rudouglas** [comment]
https://github.com/newrelic/docs-website/pull/4710

@LizBaker it looks like we can just add this to each individual page we want the search for, but not 100% sure if that is something we want to do, or if it makes more sense than putting it in the theme? Checkout my PR

**Comment by LizBaker** [comment]
@rudouglas I think it would be super sweet in the theme! you could add it to the theme SEO component and make it dynamic using the siteUrl which will update based on the site it's in. additionally we can make sure it's only inserted on the homepage of the site similar to how we insert crazy egg https://github.com/newrelic/docs-website/blob/develop/src/components/SEO.js

**Comment by rudouglas** [comment]
cool no worries thanks :D

**Comment by aswanson-nr** [comment]
Keeping this open while #547 gets released and merged into the sites

**Comment by rudouglas** [comment]
This is merged, once the docs site is released we can check if this is correct using https://search.google.com/test/rich-results

**Comment by rudouglas** [comment]
Yay this is now being added correctly 🥳 
https://search.google.com/test/rich-results/result/r%2Fsitelinks-searchbox?id=--ZgEt7OyvT5qRWaWHoApg

**Comment by rudouglas** [comment]
Just need this merged now https://github.com/newrelic/docs-website/pull/4848
