### ISSUE TITLE
audit external links to determine where we show the external link icon

### ISSUE THREAD

**Issue by jpvajda** [newrelic/gatsby-theme-newrelic#517]
Relates to https://github.com/newrelic/gatsby-theme-newrelic/issues/497

Now that we have the ability to set the external link icon by a prop, we will want to evaluate where it makes sense to show this icon for the external links an all our Gatsby sites. 

### Design Questions 

- [ ] Where does it make sense to use the external link icon?
- [ ] Where does it not make sense to use the external link icon
- [ ] if it's docs, oss, or dev site should it have an external link or not?
- [ ] if it's blog or newrelic.com, is that an external link? 

### Acceptance Criteria

- [ ] TBD

**Comment by legnaleama** [comment]
Here's the design research on this: https://www.figma.com/file/0jsTPLtwz6Bljndkbr1COn/?node-id=339%3A9078

TLTR:
**SOLUTION**

**A - Quick fix**
Add ”new tab/external” icon to all external links in both developer.newrelic.com and docs.newrelic.com

**B - Medium fix**
Stop loading pages that share the navbar on a new tab to avoid creating the experience of being in a new site.

By allowing users to perceive each of the links on the navbar as sections of the same website we'll remove the need to indicate links pointing to docs.newrelic.com as external when used in the Developers site and vice versa.

This would reduce the cognitive strain and simplify the experience but it won't solve the current content maze.

**C - Large fix**
Merge Developers and Docs content and re-structure content in a way that makes it accessible and easy to find (when the user needs it).

By merging both sites and creating a robust and intuitive content structure we'll reduce significantly the amount of ”external” links and we'll streamline access to troubleshooting to those users who are looking for answers.

External links will stop being the majority (in the case of Developers) and therefore indicating those that are actually really external we'll make the whole UX more robust and user friendly.
