### ISSUE TITLE
[Gatsby Sites] 🔐 Authentication [Q1 Priority]

### ISSUE THREAD

**Issue by zstix** [newrelic/gatsby-theme-newrelic#530]
### Epic Milestones

Across all Gatsby sites a user should be able to use their New Relic user credential to authenticate and login to the following sites.

- opensource.newrelic.com
- docs.newrelic.com.
- developer.newrelic.com

Sessions should be shared so the user doesn’t have to re-login as they visit different sites.

### Epic Plan 

https://docs.google.com/document/d/1GOMdL7gfMwvZ8KdfcD-iO4sdnhvzUUtmN8LibQDaMCI/edit

**Comment by jpvajda** [comment]
closing this epic as docs engineering is moving into JIRA
