### ISSUE TITLE
[Theme] Convert all Browser pageAction events to Tessen Events

### ISSUE THREAD

**Issue by jpvajda** [newrelic/gatsby-theme-newrelic#534]
All of New Relic is moving to standardize on the use of TessenAction events so we have a single source of analytic event truth.  This is company wide initiative so we've been ask to consider this change for our external sites. 

These changes would apply to : Theme / Docs / OSS / Dev

### Acceptance Criteria 

**Business decisions**

- [x] what about quickstarts in product details? Confirm we don't use Browser pageActions there. 
- [x] Confirm with @cdang if there are other events that we need to build, or any other changes that are expected- @polfliet 
- [x] Confirm the impacts to Segment costs and if this is approved - @polfliet 
- [x] Confirm what additions event data needs to be passed via tessen? - @polfliet 
- [x] Confirm how data governance will occur to decide what to instrument - @polfliet 

**Engineering**

- [x] Estimate how many daily events we may now be sending over through segment (ex: link clicks)

Note segment would only count an event for a new user as it's based on MAUs, so below these numbers are the total count of events we'd be sending to Segment, which many would be triggered by an existing MAU.

> 310k a month (docs)
> 26k a month (dev site)
> 1k a month (oss site)
> 400k a month

- [ ] Lead a DevEn team session to walk through the world of tessen / segment / browser so it's clear how this works.
- [ ] change the existing PageAction events to TessenAction 
- [ ] add a check for formatting of category and event name
- [ ] update documentation wikis for both the [dev site]() and [docs site](https://github.com/newrelic/docs-website/wiki/Event-Data--and--Instrumentation)
- [ ] update all dashboards found here: 

- [DevEn] External I/O & Quickstarts Ecosystem
- New Relic I/O Program Dashboard
- [DevEn] Docs Ecosystem

- [ ] resolve any analytic issues from this change that - will be new bugs filed when reported

**Comment by jpvajda** [comment]
@polfliet we have several questions to work through before we can estimate, we can discuss this as needed.

**Comment by jpvajda** [comment]
@zstix was going to dig into this a little further to understand the scope / expectations on this request.

**Comment by jpvajda** [comment]
I've dropped a slack message in #project-tessen waiting for some input.

**Comment by zstix** [comment]
I did a little digging into this, here's some preliminary answers to some of those questions / concerns:

> What about quickstarts in product details? Confirm we don't use Browser pageActions there.

We are _only_ using Tessen for our work in the product, so we wont need to make any adjustments to that code.

> Confirm the impacts to Segment costs and if this is approved

My account doesn't have access to billing, but based on [Segment's pricing](https://segment.com/pricing/), I don't think we will need to worry about any impact. We wont be _adding_ new visitors and we are already set up for unlimited sources. According to [our documentation](https://github.com/newrelic/docs-website/wiki/Event-Data--and--Instrumentation), we already send a good deal of instrumentation data that way. Short answer: no impact.

> Confirm what additions event data needs to be passed via tessen?

Some information maps pretty cleanly from our Browser agent's `pageAction` to Tessen's `track`:

| Browser PageAction | Tessen track | Description |
| - | - | - |
| `actionName` | `eventName` | The event that's being tracked (straightforward swap) |
| `attributes` | `properties` | Event information (we can add the extra fields here) | 
| n/a | `properties.location` | "Public" or "Private" (we can hard-code) |
| n/a | `properties.nr_product` | 3-4 letter identifier (e.g. DOC, set in the theme config) |
| n/a | `properties.nr_subproduct` | 3-4 letter identifier (e.g. TDOC, set in the theme config) |
| n/a | `properties.category` | ??? |

The only thing we would need to come up with is the `category` for each event. At the moment, we only use this for page views and we have every event use a generic `PageView` category. We could either 1️⃣  have a generic `pageAction` category or 2️⃣  come up with custom categories (which would require some decision making).

---

Given the above information, I feel like we have enough details to build out some tickets for this work. Most of our instrumentation is handled by the theme and I think it would be pretty straightforward to implement this (with some assumptions). Ballpark estimate of a couple days? Maybe?

cc: @jpvajda

**Comment by jpvajda** [comment]
@zstix great work on this !

> We could either 1️⃣ have a generic pageAction category or 2️⃣ come up with custom categories (which would require some decision making

interesting question, this is where I was asking about "_data governance and standardization_" to the approach.  And if anyone is defining this level of detail. But in the spirit of agile we can go with option 1️⃣  and always add custom categories later based on need. 

`Question:` Is this work large enough that it needs seperate tickets or can we just break all down here as this has a lot of useful information already?

**Comment by jpvajda** [comment]
This ticket will be broken out into multiple tickets.... but as it stands it a 5 to an 8

**Comment by jpvajda** [comment]
@LizBaker to break up tickets. 👋

**Comment by jpvajda** [comment]
marking as closed as we broke this ticket up.
