### ISSUE TITLE
[Theme] Instrument links in related resources so we can measure clicks

### ISSUE THREAD

**Issue by jpvajda** [newrelic/gatsby-theme-newrelic#538]
### Issue

instrument related resources so we know who clicked on what and where and this click can it be tied to a conversion such as install or a sign up of a new user

We currently instrument the clicks with a tessen event called [relatedResourcesLinkClick](https://github.com/newrelic/gatsby-theme-newrelic/blob/bbf50b58854a57af6c2488caf3569901ed1a55fa/packages/gatsby-theme-newrelic/src/components/RelatedResources.js#L91) but do we `DO NOT` know where this linked was clicked and how often?

### Question:

- Do quickstarts surfaced in related resources drive conversions for sign ups or installations?

### Acceptance Criteria 

- [x] The source page URL of where the link was clicked is available in the event
- [x]  The page URL the  user was sent to is available in the event

**Comment by zstix** [comment]
Here's a query to get all the events with the `relatedResourcesLinkClick` interaction type: https://staging.onenr.io/0PLREMKboRa

**Comment by jpvajda** [comment]
I mocked out a dashboard component to visualize this  data when this work is done, `I/O Related Resources Clicks (WIP)` it's here: https://staging.onenr.io/0nVjYbDAqQ0
