### ISSUE TITLE
[Theme] Replace all instrumentation with tessen

### ISSUE THREAD

**Issue by LizBaker** [newrelic/gatsby-theme-newrelic#559]
We're fully removing events fired by the browser agent and replacing them with tessen actions.

### Acceptance Criteria

- [x] Remove `useInstrumentedData` hook (check for any uses in the opensource/dev/docs sites or theme first but I didn’t find any)
- [x] remove all browser agent page actions from the theme
- [x] Edit `useInstrumentedHandler` code to remove browser option/fallback (we don’t need to pass an agent argument anymore)
  - [x] Check and update the use of `useInstrumentedHandler` in any theme components
  - [x] Check and update the `instrumentation` prop on any theme components
  - [x] Add warnings to `useInstrumentedHandler` for malformed category or event names 
  * `eventName` is camelCase
  * `category` is Title Case
- [x] Add warnings to createtessen.js for malformed category or event names
  - example regex checks can be found in `project-tessen:source/lib/constants.js#L93-L94`
- [x] Update any tests affected
- [x] Update any documentation/wiki references to the browser events. Remove the documentation for `useInstrumentedData`
- [ ] Update any dashboards tracking browser events from theme components (here are the most important)
* [DevEn] External I/O & Quickstarts Ecosystem
* New Relic I/O Program Dashboard
* [DevEn] Docs Ecosystem

**Comment by jpvajda** [comment]
@roadlittledawn mentioned that we need to verify the theme is not sending any browser agent page actions..

**Comment by roadlittledawn** [comment]
looks like the theme sends two `PageAction` actions called:
- `navInteraction`
- `swiftypeSearch_input`

**Comment by rudouglas** [comment]
Leaving this in open for now, once all the sites are updated with the new theme we'll do one final pass to check the charts are all correct

**Comment by zstix** [comment]
We're going to update the dashboards as we complete the other tickets.
