### ISSUE TITLE
[Theme] Use an anonomous ID to generate the event data we need for conversion funnels.

### ISSUE THREAD

**Issue by jpvajda** [newrelic/gatsby-theme-newrelic#563]
### Example query with the anonymous ID

```sql
FROM TessenAction SELECT filter(uniqueCount(anonymousId), WHERE eventName = 'TLMK_SignUp_signup'), filter(uniqueCount(anonymousId), WHERE eventName = 'TLMK_SignUp_signupThankYou') TIMESERIES AUTO SINCE 1 month ago
````

### Acceptance Criteria

- [x] Discuss with PLG how they get the anonymous ID , is it from segment? - `#help-plg` slack channel
- [ ] Determine how we can use this ID to generate the event data we need for conversion funnels.
- [ ] Once confirmed, add the anonymous ID to all events via the theme

**Comment by rudouglas** [comment]
Asking in #help-plg on this, will update with more details

**Comment by jpvajda** [comment]
@rudouglas could you add me to the thread, I'm interested in their reply.

**Comment by rudouglas** [comment]
>The anonymousId comes from Segment—at least on the signup page (which is a repo that PLG built, but is transitioning ownership to #help-signup). On the signup page, [here's the source for how we get anonymousId](https://source.datanerd.us/plg/tillamook/blob/4bd42875fe0c5851f9050ea5b9ef09f2cf82f533/src/utils/tessen.js#L20-L31).
For more info, I'd suggest asking in #project-tessen or #wizards-amplitude to see if someone else knows more.
