### ISSUE TITLE
(Mobile) Width not consistent on certain displays

### ISSUE THREAD

**Issue by josephgregoryii** [newrelic/gatsby-theme-newrelic#586]
On certain mobile devices across the sites, the header and footer width get reduced down to what looks like less than `100%`. It looks like this bug starts to occur somewhere between the width `280px` and `325px`.

___

### Header
<details>
<summary>Light mode</summary>

![Header-light-mode](https://user-images.githubusercontent.com/56952981/143088257-67f7fa01-b008-4c2b-af8f-45de1fc9ba9d.png)

</details>

<details>
<summary>Dark mode</summary>

![Header-dark-mode](https://user-images.githubusercontent.com/56952981/143088126-88e08e5a-d6e4-4d80-9118-926e3b923fbe.png)

</details>

____

### Footer

<details>
<summary>Light Mode</summary>

![Screen Shot 2021-11-23 at 11 10 43 AM](https://user-images.githubusercontent.com/56952981/143089088-e82bef2f-6a76-401c-ac80-9cd37b12d355.png)

</details>

<details>
<summary>Dark Mode</summary>

![Screen Shot 2021-11-23 at 11 00 34 AM](https://user-images.githubusercontent.com/56952981/143089060-897894a4-1ca4-46df-a6ab-638e897eed0c.png)

</details>

**Comment by jpvajda** [comment]
is this even a standard mobile width though?

```
According to the Worldwide Screen Resolution Stats (Jan 2020 – Jan 2021), the most commonly used resolutions across mobile, desktop, and tablet are: 1920×1080 (8.89%) 1366×768 (8.44%) 360×640 (7.28%)
```
https://www.browserstack.com/guide/ideal-screen-sizes-for-responsive-design

**Comment by jpvajda** [comment]
We will close this out based on the data above.

**Comment by jpvajda** [comment]
after further discussions, we decided to keep it open and make a low priority bug.
