### ISSUE TITLE
GlobalHeader mobile: Missing login & language buttons

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/gatsby-theme-newrelic#590]
## Summary

The global header redesign, #510, loses some functionality on layouts with smaller widths. 

### Current design

<img width="320" alt="Screen Shot 2021-11-23 at 3 19 31 PM" src="https://user-images.githubusercontent.com/70179303/143144069-92fdeab2-2492-4168-93b6-58a9a433fd9e.png">

`This includes buttons for:`

-  docs, dev, oss, learn, etc
- search
- language
- theme
- login
- signup

### The new design

<img width="380" alt="Screen Shot 2021-11-23 at 3 21 17 PM" src="https://user-images.githubusercontent.com/70179303/143144268-5dac6d85-ed70-4a9f-9991-3e39dc076585.png">

`This includes buttons for:`

- docs, dev, oss, learn, etc
- search
- theme
- signup
- language ❓ 
- login ❓ 

## AC
- [x] Confirm if the removal of this functionality for the language and login buttons on mobile is intentional
- [ ] `IF NOT` intentional, work with design to determine how the header should be laid out
- [x] `IF` intentionally, close this out as won't fix.

**Comment by jpvajda** [comment]
@legnaleama for input here. 👋

**Comment by rudouglas** [comment]
As per @legnaleama this is intentional for the moment, so closing this out
