### ISSUE TITLE
Improve split test rendering "flash" `part 2`

### ISSUE THREAD

**Issue by jpvajda** [newrelic/gatsby-theme-newrelic#616]
Relates to https://github.com/newrelic/docs-website/issues/5165

our conclusion in part of 1 of this work is that it's not currently possible to instantly load the correct treatment for a split test when the page loads, this is because we have to wait for the splitSDK to communicate with the API which we can't speed up client side. The alternative would be waiting until the SDK is ready to load the entire page, which wouldn't be great for UX. Our recommendations are as follows:

### Skeleton approach 

> a grey box that transitions into the component smoothly. 

### Acceptance Criteria 

- [ ]  Load a skeleton component in place of the treatment component with some sort of indicator that a component is currently loading (Spinner, animation etc.). This is so that there is no shift in real estate when the component loads and no flash between content loads
- [ ]  Use the caching feature of the SDK so that this load only happens once per user, and the treatment is loaded from local storage every other time. This should apply across products as well (@josephgregoryii is currently testing this)
- [ ]  Use the `isTimeOut` feature of the SDK so that we know to eventually render the default component
- [ ]  Confirm with Gatsby when they will support[ A/B Branch testing ](https://portal.gatsbyjs.com/gatsby-cloud/p/ab-testing-support)
- [ ] Verify font does not change in Chrome (per demo feedback)

**Comment by jpvajda** [comment]
@legnaleama we'd just need a design for the "skeleton" component we'd load in this case, if a spinner element isn't enough.

**Comment by josephgregoryii** [comment]
@jpvajda @rudouglas @AlecIsaacson I was able to get `LOCALSTORAGE` set for split, with the help of @clarkmcadoo. The solution to this was to upgrade split from `1.2.4` -> `1.3.0` I was able to upgrade the `splitio-react`package on a testing branch. I would want to make sure I upgrade the version correctly if someone would want to assist that.

### Steps to reproduce storage:

```js
        splitio: {
          storage: {
            type: 'LOCALSTORAGE',
            prefix: 'THEME_DEMO',
          },
          debug: false,
        },
```

**Comment by jpvajda** [comment]
@legnaleama  one more design question for you...

**Comment by jpvajda** [comment]
blocked until we have a design on the skeleton component

**Comment by jpvajda** [comment]
we'll take an approach with the 💀 component and @legnaleama would review our approach.

**Comment by roadlittledawn** [comment]
Moved to jira https://newrelic.atlassian.net/browse/DOCENG-13
