### ISSUE TITLE
Separate translations, locales from theme

### ISSUE THREAD

**Issue by MoonlightKomorebi** [newrelic/gatsby-theme-newrelic#639]
## Summary

This ticket is a proposal to change some of the code architecture around adding a new language for a site. In particular, if a site wants to support a new language, you have to make changes in both the site and theme. The proposal here is to change this so that ultimately only a change to the site is needed, and the theme can just get what it needs from configuration. If it is not possible to completely isolate the theme, then we want as minimal a touchpoint as possible. It may be the case that we think this current setup is fine, or additional changes are not warranted.

## Background
<details>

At the moment, in order to add a new language -- like korean -- we have to make a change in the theme and the site in the following places.

In the site, the touchpoint we have to change is: https://github.com/newrelic/docs-website/blob/e6a23aaa275012db5c3146dae97c9fbbcf5ce2cf/gatsby-config.js#L11

In the theme, the touchpoint we have to change is: https://github.com/newrelic/gatsby-theme-newrelic/blob/5ed6b6f8537d088c0273b845dde4891c58292a19/packages/gatsby-theme-newrelic/src/utils/config/i18n.js#L1-L59

Additionally, for components that live in the theme, we need to provide translations for static text within those components, which is defined here: https://github.com/newrelic/gatsby-theme-newrelic/tree/develop/packages/gatsby-theme-newrelic/src/i18n/translations

</details>

## Proposed Changes / Starting points

<details>

- Change code in i18n.js so that the locales/languages the theme uses are entirely supplied by the site. Update code in the site to supply locale objects that are currently internal to the theme.
  - in the theme, rather than accept 'jp' or 'kr', we accept the whole locale object.
  - in the site, rather than pass in a string of code, we pass in the whole locale object.
  - if we want to make this backwards compatible and not be a breaking change, we can consider adding in a new option, or having the existing option work with either input.
- Remove src/i18n/translations from theme. Have this be supplied by the site.
  - I'm not sure if this is easy / hard. Will need some research to understand how this is setup, how to change it, and the impact of that change.

</details>

## Acceptance Criteria
- [ ] TBD

**Comment by nr-kkenney** [comment]
@zstix here is my initial attempt at the ticket 🙈
