### ISSUE TITLE
[Gatsby Theme] canonical url issue with theme and I/O site home page

### ISSUE THREAD

**Issue by jpvajda** [newrelic/gatsby-theme-newrelic#648]
We're seeing an issue on the `newrelic.com/instant-observability` home page where a slash is being added to the end of the URL upon page visit.  We believe this is coming from the theme, and needs to be removed in for SEO purposes. Specifically, we need to canonical url to match the actual url on the I/O homepage.

- [ ] fix theme from adding slash to canonical url
- [ ] ensure this doesn't affect our other sites using the Gatsby theme
- [ ] run a manual indexing of swifttype? we were able to do this to test the quickstart pages, but idk if this will work with the home page, ask @roadlittledawn 
- [ ] if AC 3 doesn't work, you can simply look in the html `<head>` for `<link data-react-helmet="true" rel="canonical" href="https://newrelic.com/instant-observability/">`

**Comment by roadlittledawn** [comment]
Moved to jira https://newrelic.atlassian.net/browse/DOCENG-25
