### ISSUE TITLE
Opening the search overlay does not autofocus the input

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/gatsby-theme-newrelic#84]
## Description

Opening the search overlay by clicking the search icon in the header does not autofocus the input. It would be great to focus the input so that the user can just begin typing their search query without first needing to click on the input.

## Steps to Reproduce

1. Click the search icon in the header
2. Notice the input is not focused

## Expected Behaviour

The input is auto focused after opening the search overlay

**Comment by zstix** [comment]
This is no longer relevant for the desktop experience, due to us removing the search icon. On mobile, this is still an issue because the input is not focused when tapping on the search icon.
