### ISSUE TITLE
Documentation for global color variables 

### ISSUE THREAD

**Issue by caylahamann** [newrelic/gatsby-theme-newrelic#90]
# Documentation for global color variables

## Summary

As noticed in a PR to our developer website, we don't have the best documentation surrounding our global color variables. I wonder if we would be able to link to our color guide / style guide so contributors creating new components are able to reference them!

**Comment by jerelmiller** [comment]
Here's some context on the comment: https://github.com/newrelic/developer-website/pull/675/files/700ca4b356d9abc1480d4fade3aff87cda86da59#diff-faacae4e5e261a5839e04cc5a76f9467
